# Generated by Django 2.1.5 on 2019-01-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gdpr', '0003_add_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizeddata',
            name='expired_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='gdpr.LegalReason', verbose_name='expired reason'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymizeddata',
            unique_together={('content_type', 'object_id', 'field')},
        ),
    ]
