# Generated by Django 2.1.5 on 2019-01-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0003'),
        ('gdpr', '0004_anon_data_unique'),
    ]

    operations = [
    ]
