# Generated by Django 2.1.5 on 2019-01-06 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='account_number',
            new_name='account',
        ),
    ]
