# Generated by Django 2.1.5 on 2019-01-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0002_rename_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
